[phases.setup]
nixPkgs = ["pnpm", "nodejs-20_x"]

[phases.build]
cmds = [
  "pnpm install",
  "PGSSLMODE=no-verify NODE_TLS_REJECT_UNAUTHORIZED=0 pnpm -F @uniconnect/shared migrate",
  "pnpm -F app build"
]

[start]
cmd = "node apps/app/build/index.js"
